# Generated by Django 4.2.11 on 2025-08-22 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversion_id', models.CharField(max_length=100, unique=True)),
                ('conversion_type', models.CharField(choices=[('XML', 'XML'), ('HL7', 'HL7')], max_length=10)),
                ('source_data', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('converted_data', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'data_conversions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DrugRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(max_length=255)),
                ('dosage', models.CharField(blank=True, max_length=100)),
                ('strength', models.CharField(blank=True, max_length=100)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('patient_id', models.CharField(blank=True, max_length=100)),
                ('prescription_id', models.CharField(blank=True, max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drug_records', to='data_converter.dataconversion')),
            ],
            options={
                'db_table': 'drug_records',
                'ordering': ['-created_at'],
            },
        ),
    ]
