# Generated by Django 5.2.5 on 2025-08-24 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_converter', '0002_patient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100, unique=True)),
                ('device_type', models.CharField(choices=[('RFID_READER', 'RFID Reader'), ('BLUETOOTH_DEVICE', 'Bluetooth Device'), ('BARCODE_SCANNER', 'Barcode Scanner')], max_length=20)),
                ('device_name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('ERROR', 'Error'), ('MAINTENANCE', 'Maintenance')], default='OFFLINE', max_length=20)),
                ('battery_level', models.IntegerField(blank=True, null=True)),
                ('last_connected', models.DateTimeField(blank=True, null=True)),
                ('last_disconnected', models.DateTimeField(blank=True, null=True)),
                ('connection_status', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'device_status',
                'ordering': ['-last_connected'],
            },
        ),
        migrations.CreateModel(
            name='DrugInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfid_tag', models.CharField(max_length=100, unique=True)),
                ('drug_name', models.CharField(max_length=255)),
                ('dosage', models.CharField(blank=True, max_length=100)),
                ('strength', models.CharField(blank=True, max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('batch_number', models.CharField(blank=True, max_length=100)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('LOW_STOCK', 'Low Stock'), ('OUT_OF_STOCK', 'Out of Stock'), ('RECALLED', 'Recalled')], default='ACTIVE', max_length=20)),
                ('last_scanned', models.DateTimeField(blank=True, null=True)),
                ('last_scanned_by', models.CharField(blank=True, max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'drug_inventory',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdministrationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('administered_by', models.CharField(blank=True, max_length=100)),
                ('administration_time', models.DateTimeField()),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('dosage_administered', models.CharField(blank=True, max_length=100)),
                ('route', models.CharField(blank=True, choices=[('ORAL', 'Oral'), ('IV', 'Intravenous'), ('IM', 'Intramuscular'), ('SC', 'Subcutaneous'), ('TOPICAL', 'Topical'), ('INHALATION', 'Inhalation'), ('OTHER', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('ADMINISTERED', 'Administered'), ('MISSED', 'Missed'), ('CANCELLED', 'Cancelled'), ('REFUSED', 'Refused')], default='SCHEDULED', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('verification_method', models.CharField(blank=True, max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrations', to='data_converter.patient')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrations', to='data_converter.druginventory')),
            ],
            options={
                'db_table': 'administration_records',
                'ordering': ['-administration_time'],
            },
        ),
    ]
